cache:
  paths:
    - ccache/

before_script:
 - apt update >/dev/null && apt install -y git >/dev/null
 - git clone https://gitlab.com/VictorLamoine/ros_gitlab_ci.git
 - source ros_gitlab_ci/gitlab-ci.bash >/dev/null

# kinetic
kinetic_catkin_build:
  image: ros:kinetic-robot
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
    - catkin run_tests --no-status --force-color

# melodic
melodic_catkin_build:
  image: ros:melodic-robot
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
    - catkin run_tests --no-status --force-color

# noetic
noetic_catkin_build:
  image: ros:noetic-robot
  stage: build
  script:
    - catkin build --summarize --no-status --force-color
    - catkin run_tests --no-status --force-color
